FROM milic/jenkins-agent:make
USER root
RUN apt-get update && apt-get install -y  

# Set environment variables for Go
ENV GOLANG_VERSION 1.21.6
ENV GOPATH /go
ENV PATH \$GOPATH/bin:/usr/local/go/bin:\$PATH

# Install Go
RUN curl -fsSLo golang.tar.gz "https://go.dev/dl/go1.21.6.linux-amd64.tar.gz"  
RUN tar -C /usr/local -xzf golang.tar.gz 
RUN rm golang.tar.gz

# Create Go workspace
RUN mkdir -p "\$GOPATH/src" "\$GOPATH/bin" && chmod -R 777 "\$GOPATH"

# Verify that Go is installed
RUN go version


# Switch back to jenkins user
USER jenkins

ENTRYPOINT ["/usr/local/bin/jenkins-agent"]