apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko
spec:
  completions: 1
  backoffLimit: 1
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args: ["--dockerfile=/simple-go-app/Dockerfile",
               "--context=git://github.com/gscho/simple-go-app.git",
               "--destination=milic/appgo:latest",
               "--cache=true"]
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker
      restartPolicy: Never
      volumes:
        - name: kaniko-secret
          secret:
            secretName: reg-credentials
            items:
              - key: .dockerconfigjson
                path: config.json
